version: '3'
services:
  amc:
    image: amazechain/amc:latest
    command:
      - --data.dir
      - data
      - --log.level
      - info
      - --http
      - --http.port
      - '20012'
      - --http.addr
      - '0.0.0.0'
      - --ws
      - --ws.port
      - '20013'
      - --ws.addr
      - '0.0.0.0'
      - --metrics
      - --metrics.addr
      - '0.0.0.0'
      - --p2p.min-sync-peers
      - '1'
    networks:
      network1:
        ipv4_address: 172.18.0.2
    user: 1000:1000
    volumes:
      - amc:/home/amc/data
    ports:
      - "20012:20012"
      - "20013:20013"

  prometheus:
    image: prom/prometheus:v2.47.0
    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}
    command: --log.level=warn --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --storage.tsdb.retention.time=150d --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles
    ports: [ "9090:9090" ]
    volumes:
      - ${AMC_PROMETHEUS_CONFIG:-./deployments/prometheus/prometheus.yml}:/etc/prometheus/prometheus.yml
      - ${XDG_DATA_HOME:-~/.local/share}/amc-prometheus:/prometheus
    restart: unless-stopped
    networks:
      network1:
        ipv4_address: 172.18.0.9

  grafana:
    image: grafana/grafana:10.1.2
    user: "472:0" # required for grafana version >= 7.3
    ports: [ "3000:3000" ]
    volumes:
      - ${AMC_GRAFANA_CONFIG:-./deployments/prometheus/grafana.ini}:/etc/grafana/grafana.ini
      - ./deployments/prometheus/datasources:/etc/grafana/provisioning/datasources
      - ./deployments/prometheus/dashboards:/etc/grafana/provisioning/dashboards
      - ${XDG_DATA_HOME:-~/.local/share}/amc-grafana:/var/lib/grafana
    restart: unless-stopped
    networks:
      network1:
        ipv4_address: 172.18.0.10

networks:
  network1:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
volumes:
  amc:
    driver: local
