version: '3'
services:
  bootnode:
    image: amazechain/amc:latest
    container_name: bootnode
    command:
      - AmazeChain-linux-amd64
      - --data.dir
      - data
      - --p2p.listen
      - '/ip4/172.18.0.2/tcp/61016'
      - --p2p.key
      - 'CAMSeTB3AgEBBCBZandzyO1LLLNawa6diRUh/A7FTOkxLlHuaIaQJ2piDqAKBggqhkjOPQMBB6FEA0IABEhI/zTNfeaDp31XUoGwUACXZ1HswgWtJGxYoqq9CIxfEvMl3HnMn2ZVcSz2z590k/CpfnrsTLik/8dUiXBfh2U='
      - --log.level
      - info
      - --http
      - --http.port
      - '20012'
      - --http.addr
      - 172.18.0.2
      - --ws
      - --ws.port
      - '20013'
      - --ws.addr
      - 172.18.0.2
      - --engine.miner
      - --engine.etherbase
      - '0x6280240DF26Ccda30aFccB3ba7a1929Bf49e15C9'
      - --account.unlock
      - '0'
      - --account.allow.insecure.unlock
      - --account.password
      - './password'
    networks:
      network1:
        ipv4_address: 172.18.0.2
    user: 1000:1000
    volumes:
      - /Users/mac/node:/home/amc/data/
      - ./deployments/keystore:/home/amc/data/keystore:ro
      - ./deployments/keystore/password:/home/amc/password:ro
    ports:
      - "20012:20012"
      - "20013:20013"
  node:
    image: amazechain/amc:latest
    container_name: node1
    command:
      - AmazeChain-linux-amd64
      - --data.dir
      - data
      - --p2p.bootstrap
      - '/ip4/172.18.0.2/tcp/61016/p2p/QmRFiu3yisZdfySiRLRhjDcD3ZLeteEo31R9mmKudDhP53'
      - --p2p.listen
      - '/ip4/172.18.0.3/tcp/61016'
      - --log.level
      - info
      - --http
      - --http.port
      - '20112'
      - --http.addr
      - 172.18.0.3
      - --engine.miner
      - --engine.etherbase
      - '0x6a0496E96fC3A1E9984C6b9b9e0d37b39DC8b09D'
      - --account.unlock
      - '1'
      - --account.allow.insecure.unlock
      - --account.password
      - './password'
      - --p2p.tcp-port
      - '61020'
      - --p2p.udp-port
      - '61021'
      - --p2p.bootstrap-node
      - 'enr:-Iu4QHJisJBXXAaZ8gkiqT8_qDRmsGjhbhazYcyMSuP4B3KmSGzqtiQEwD-RsptVG_oUXmSiMzRXNgunzikiz8-wjt4BgmlkgnY0gmlwhKwSAAKJc2VjcDI1NmsxoQPWCxC2Yx8ENgG-kHZ2b_N9eFlFMj6SlAiJzFMMchH6QoN0Y3CC7liDdWRwgu5X'
    depends_on:
      - bootnode
    networks:
      network1:
        ipv4_address: 172.18.0.3
    volumes:
      - /Users/mac/node1:/home/amc/data
      - ./deployments/keystore:/home/amc/data/keystore:ro
      - ./deployments/keystore/password:/home/amc/password:ro
    ports: [ "20112:20112" ]
  node2:
    image: amazechain/amc:latest
    container_name: node2
    command:
      - AmazeChain-linux-amd64
      - --data.dir
      - data
      - --p2p.bootstrap
      - '/ip4/172.18.0.2/tcp/61016/p2p/QmRFiu3yisZdfySiRLRhjDcD3ZLeteEo31R9mmKudDhP53'
      - --p2p.listen
      - '/ip4/172.18.0.4/tcp/61016'
      - --log.level
      - info
      - --http
      - --http.port
      - '20212'
      - --http.addr
      - 172.18.0.4
      - --engine.miner
      - --engine.etherbase
      - '0x8Cb83482cDF222f261D0CB282658351C5cAd75B9'
      - --account.unlock
      - '2'
      - --account.allow.insecure.unlock
      - --account.password
      - './password'
      - --p2p.tcp-port
      - '61030'
      - --p2p.udp-port
      - '61031'
      - --p2p.bootstrap-node
      - 'enr:-Iu4QHJisJBXXAaZ8gkiqT8_qDRmsGjhbhazYcyMSuP4B3KmSGzqtiQEwD-RsptVG_oUXmSiMzRXNgunzikiz8-wjt4BgmlkgnY0gmlwhKwSAAKJc2VjcDI1NmsxoQPWCxC2Yx8ENgG-kHZ2b_N9eFlFMj6SlAiJzFMMchH6QoN0Y3CC7liDdWRwgu5X'
    depends_on:
      - bootnode
    networks:
      network1:
        ipv4_address: 172.18.0.4
    volumes:
      - /Users/mac/node2:/home/amc/data
      - ./deployments/keystore:/home/amc/data/keystore:ro
      - ./deployments/keystore/password:/home/amc/password:ro
    ports: [ "20212:20212" ]
  downloader:
    image: amazechain/amc:latest
    container_name: downloader
    depends_on:
      - node2
    command:
      - AmazeChain-linux-amd64
      - --data.dir
      - data
      - --p2p.bootstrap
      - '/ip4/172.18.0.2/tcp/61016/p2p/QmRFiu3yisZdfySiRLRhjDcD3ZLeteEo31R9mmKudDhP53'
      - --p2p.listen
      - '/ip4/172.18.0.5/tcp/61016'
      - --log.level
      - info
      - --http
      - --http.port
      - '20312'
      - --http.addr
      - 172.18.0.5
      - --p2p.tcp-port
      - '61040'
      - --p2p.udp-port
      - '61041'
      - --p2p.bootstrap-node
      - 'enr:-Iu4QHJisJBXXAaZ8gkiqT8_qDRmsGjhbhazYcyMSuP4B3KmSGzqtiQEwD-RsptVG_oUXmSiMzRXNgunzikiz8-wjt4BgmlkgnY0gmlwhKwSAAKJc2VjcDI1NmsxoQPWCxC2Yx8ENgG-kHZ2b_N9eFlFMj6SlAiJzFMMchH6QoN0Y3CC7liDdWRwgu5X'
    networks:
      network1:
        ipv4_address: 172.18.0.5
    volumes:
      - db_downloader_1:/home/amc/data
      - ./deployments/keystore:/home/amc/data/keystore:ro
    ports: [ "20312:20312" ]
networks:
  network1:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
volumes:
  db_downloader_1:
    driver: local
