// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types.proto

package state

import (
	fmt "fmt"
	github_com_amazechain_amc_common_types "github.com/amazechain/amc/common/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type HashMap struct {
	Key                  github_com_amazechain_amc_common_types.Hash `protobuf:"bytes,1,opt,name=key,proto3,customtype=github.com/amazechain/amc/common/types.Hash" json:"key"`
	Value                github_com_amazechain_amc_common_types.Hash `protobuf:"bytes,2,opt,name=value,proto3,customtype=github.com/amazechain/amc/common/types.Hash" json:"value"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *HashMap) Reset()         { *m = HashMap{} }
func (m *HashMap) String() string { return proto.CompactTextString(m) }
func (*HashMap) ProtoMessage()    {}
func (*HashMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}
func (m *HashMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashMap.Unmarshal(m, b)
}
func (m *HashMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashMap.Marshal(b, m, deterministic)
}
func (m *HashMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashMap.Merge(m, src)
}
func (m *HashMap) XXX_Size() int {
	return xxx_messageInfo_HashMap.Size(m)
}
func (m *HashMap) XXX_DiscardUnknown() {
	xxx_messageInfo_HashMap.DiscardUnknown(m)
}

var xxx_messageInfo_HashMap proto.InternalMessageInfo

type Account struct {
	Nonce    uint64                                        `protobuf:"varint,1,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Balance  github_com_amazechain_amc_common_types.Int256 `protobuf:"bytes,2,opt,name=Balance,proto3,customtype=github.com/amazechain/amc/common/types.Int256" json:"Balance"`
	Root     github_com_amazechain_amc_common_types.Hash   `protobuf:"bytes,3,opt,name=Root,proto3,customtype=github.com/amazechain/amc/common/types.Hash" json:"Root"`
	CodeHash []byte                                        `protobuf:"bytes,4,opt,name=CodeHash,proto3" json:"CodeHash,omitempty"`
	Suicided bool                                          `protobuf:"varint,5,opt,name=Suicided,proto3" json:"Suicided,omitempty"`
	//  bytes State = 6 [(gogoproto.customtype) = "github.com/amazechain/amc/common/types.HashMap", (gogoproto.nullable) = false];
	State                []*HashMap `protobuf:"bytes,6,rep,name=State,proto3" json:"State,omitempty"`
	Code                 []byte     `protobuf:"bytes,7,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Account) GetCodeHash() []byte {
	if m != nil {
		return m.CodeHash
	}
	return nil
}

func (m *Account) GetSuicided() bool {
	if m != nil {
		return m.Suicided
	}
	return false
}

func (m *Account) GetState() []*HashMap {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *Account) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func init() {
	proto.RegisterType((*HashMap)(nil), "types.pb.HashMap")
	proto.RegisterType((*Account)(nil), "types.pb.Account")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x41, 0x4a, 0xf3, 0x40,
	0x1c, 0xc5, 0xbf, 0xb4, 0x49, 0x93, 0x6f, 0xea, 0xc6, 0xa1, 0x8b, 0xa1, 0x9b, 0x86, 0x6e, 0x0c,
	0xa8, 0x19, 0x68, 0xa9, 0x7b, 0x23, 0xa2, 0x5d, 0xa8, 0x30, 0xdd, 0xb9, 0x9b, 0x4c, 0x86, 0x24,
	0x98, 0xe4, 0x1f, 0xcc, 0x44, 0xa8, 0x57, 0xf1, 0x0e, 0x9e, 0xc3, 0x33, 0xb8, 0xe8, 0x59, 0x64,
	0x26, 0x69, 0x77, 0x82, 0x74, 0x37, 0xef, 0xff, 0x98, 0xdf, 0x7b, 0xf0, 0xd0, 0x58, 0x6d, 0x6b,
	0xd9, 0x84, 0xf5, 0x2b, 0x28, 0xc0, 0x5e, 0x2f, 0xe2, 0xe9, 0x24, 0x85, 0x14, 0xcc, 0x91, 0xea,
	0x57, 0xe7, 0xcf, 0x3f, 0x2c, 0xe4, 0xde, 0xf3, 0x26, 0x7b, 0xe0, 0x35, 0xbe, 0x45, 0xc3, 0x17,
	0xb9, 0x25, 0x96, 0x6f, 0x05, 0x27, 0xd1, 0xf2, 0x6b, 0x37, 0xfb, 0xf7, 0xbd, 0x9b, 0x9d, 0xa7,
	0xb9, 0xca, 0xda, 0x38, 0x14, 0x50, 0x52, 0x5e, 0xf2, 0x77, 0x29, 0x32, 0x9e, 0x57, 0x94, 0x97,
	0x82, 0x0a, 0x28, 0x4b, 0xa8, 0x68, 0x97, 0xa0, 0x21, 0x4c, 0xff, 0xc7, 0x6b, 0xe4, 0xbc, 0xf1,
	0xa2, 0x95, 0x64, 0x70, 0x3c, 0xa8, 0x23, 0xcc, 0x3f, 0x07, 0xc8, 0xbd, 0x16, 0x02, 0xda, 0x4a,
	0xe1, 0x09, 0x72, 0x1e, 0xa1, 0x12, 0xd2, 0xf4, 0xb3, 0x59, 0x27, 0xf0, 0x13, 0x72, 0x23, 0x5e,
	0x70, 0x7d, 0xd7, 0x71, 0xff, 0xa3, 0x55, 0x1f, 0x77, 0xf9, 0xc7, 0xb8, 0x75, 0xa5, 0x16, 0xab,
	0x2b, 0xb6, 0xa7, 0xe0, 0x3b, 0x64, 0x33, 0x00, 0x45, 0x86, 0xc7, 0x97, 0x37, 0x00, 0x3c, 0x45,
	0xde, 0x0d, 0x24, 0x52, 0x5f, 0x88, 0xad, 0x61, 0xec, 0xa0, 0xb5, 0xb7, 0x69, 0x73, 0x91, 0x27,
	0x32, 0x21, 0x8e, 0x6f, 0x05, 0x1e, 0x3b, 0x68, 0x7c, 0x86, 0x9c, 0x8d, 0xe2, 0x4a, 0x92, 0x91,
	0x3f, 0x0c, 0xc6, 0x8b, 0xd3, 0x70, 0xbf, 0x60, 0xd8, 0xef, 0xc4, 0x3a, 0x1f, 0x63, 0x64, 0x6b,
	0x20, 0x71, 0x0d, 0xdc, 0xbc, 0xa3, 0xf0, 0xf9, 0xe2, 0xf7, 0xa6, 0xbc, 0xce, 0xa9, 0x59, 0x5d,
	0x40, 0x41, 0x1b, 0xcd, 0x88, 0x47, 0x46, 0x2f, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x70, 0xad,
	0x2c, 0x75, 0x34, 0x02, 0x00, 0x00,
}
